NotyMar/config/routes.rb
Rails.application.routes.draw do
  devise_for :squirrels, :controllers => { registrations: 'registrations' }
  root 'home#index'

  resources :squirrels
  resources :friendships

end

NotyMar/app/models/friendship.rb
class Friendship < ActiveRecord::Base
  belongs_to :squirrel
  belongs_to :friend, :class_name => "Squirrel"
end

NotyMar/app/models/squirrel.rb
class Squirrel < ActiveRecord::Base
  has_attached_file :picture, default_url: "specs.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :back_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :back_friends, :through => :back_friendships, :source => :squirrel
end

NotyMar/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

NotyMar/app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController
  def create
    @friendship = current_squirrel.friendships.build(:friend_id => params[:friend_id])
    if @friendship.save
      redirect_to '/squirrels'
    else
      redirect_to root_url
    end
  end

  def destroy
    @friendship = current_squirrel.friendships.find(params[:id])
    @friendship.destroy
    redirect_to current_squirrel
  end
end

NotyMar/app/controllers/home/page_controller.rb
class Home::PageController < ApplicationController
end

NotyMar/app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

NotyMar/app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

    def sign_up_params
      params.require(:squirrel).permit(:squirrel_name, :email, :password, :password_confirmation)
    end

    def account_update_params
      params.require(:squirrel).permit(:squirrel_name, :email, :password, :picture, :password_confirmation, :current_password)
    end

end

NotyMar/app/controllers/squirrels_controller.rb
class SquirrelsController < ApplicationController

  def index
    @squirrel = Squirrel.all
  end

  def show
    @squirrel = Squirrel.find(params[:id])
  end

end

NotyMar/app/helpers/application_helper.rb
module ApplicationHelper
end

NotyMar/app/helpers/home/page_helper.rb
module Home::PageHelper
end

NotyMar/app/helpers/home_helper.rb
module HomeHelper
end

NotyMar/app/views/home/index.html.erb
<div class="row">
  <%= image_tag("head.png", :alt => "Squirrel Header", class: "divider") %>
  <div class="header col-md-12">
    <div class="main-head">
      <h1>Notymar for Squirrels</h1>
      <p class="test">"Welcome to the Next Gen Squirrels"</p>
    </div>
  </div>
</div>

  <div class="body-tutorial">
    <div class="col-md-4">
      <ul class="squirrel-specs">
        <%= image_tag("specs.png", :alt => "Squirrel Header", class: "img-rounded squirrel-front-info") %>
        <li class="specs-title">Current Specs</li>
        <li><span class="glyphicon glyphicon-ok"></span> A Squirrel can Register</li>
        <li><span class="glyphicon glyphicon-ok"></span> The Squirrel can edit his information</li
        <li><span class="glyphicon glyphicon-ok"></span> The Squirrel has his own Profile</li>
        <li><span class="glyphicon glyphicon-ok"></span> List of all the Squirrels</li>
      </ul>
    </div>
    <div class=" col-md-4">
      <ul class="squirrel-specs">
        <%= image_tag("used.png", :alt => "Squirrel Header", class: "img-rounded squirrel-front-info") %>
        <li class="specs-title">Used Stuff</li>
        <li><span class="glyphicon glyphicon-fire"></span> Devise for Manage Squirrels</li>
        <li><span class="glyphicon glyphicon-fire"></span> Bootstrap</li>
        <li><span class="glyphicon glyphicon-fire"></span> Rails4 for use Notify's</li>
      </ul>
    </div>
    <div class="col-md-4">
      <ul class="squirrel-specs">
        <%= image_tag("working.png", :alt => "Squirrel Header", class: "img-rounded squirrel-front-info") %>
        <li class="specs-title">Work in Progress</li>
        <li><span class="glyphicon glyphicon-remove"></span> Style in all the Pages</li>
        <li><span class="glyphicon glyphicon-remove"></span> Load Log-in and Sign-up on Click</li>
        <li><span class="glyphicon glyphicon-ok"></span> Squirrel profile Picture</li>
        <li><span class="glyphicon glyphicon-ok"></span> A Squirrel can Add others</li>
        <li><span class="glyphicon glyphicon-remove"></span> The Squirrel can accept or deny it</li>
      </ul>
    </div>
  </div>

<div class="clear"></div>

NotyMar/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Notymar for Squirrels</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="navigation">
    <div class="container">
      <ul class="squirrel-bar">
        <li><a href="/" class="links">Home</a></li>
        <li><a href="/squirrels" class="links">Squirrels</a></li>
        <li><a href="/about" class="links">About This</a></li>
        <div class="squirrel-bar-right">
          <% if squirrel_signed_in? %>
            <li><%= link_to current_squirrel.squirrel_name, current_squirrel, class: "links" %></li>
            <li><%= link_to "Edit", "/squirrels/edit", class: "links" %></li>
            <li><%= link_to('Logout', destroy_squirrel_session_path, :method => :delete, class: "links") %></li>
          <% else %>
            <li><%= link_to('Login', new_squirrel_session_path, class: "links")  %></li>
          <% end %>
        </div>
      </ul>
    </div>
  </div>

  <div class="container web">
    <%= yield %>
  </div>

</body>
</html>

NotyMar/app/views/squirrels/index.html.erb
<h2 class="list-head">List of Squirrels</h2>
  <div class="move">
  <% @squirrel.each do |squirrel| %>
    <div class="squirrel-model">
      <div class="squirrel-add">
        <a><%= link_to squirrel.squirrel_name, squirrel, class: "links squirrel-head" %></a>
      </div>
      <div class="squirrel-data">
        <li class="lis"><%= link_to "Follow Squirrel", friendships_path(:friend_id => squirrel), :method => :post %></li>
        <li class="lis"><%= squirrel.email %></li>
      </div>
    </div>
    <% end %>
</div>

NotyMar/app/views/squirrels/show.html.erb
<%= image_tag("head.png", :alt => "Squirrel Header", class: "bg-head") %>

<div class="follow-box">
  <div class="main-head">

    <div class="pop">
      <%= image_tag(@squirrel.picture.url, :alt => "Squirrel Header", class: "img-circle squirrel-front-info") %>
    </div>

    <div class="col-md-6 follow">
      <div>
        <h3 class="follow-head">Following</h3>
        <a class="counter"><%= @squirrel.friendships.count() %></a>
      </div>
    </div>

    <div class="col-md-6 follow">
      <div>
      <h3 class="follow-head">Followers</h3>
        <a class="counter"><%= @squirrel.back_friends.count() %></a>
      </div>
    </div>

    <div class="info-profile">
      <h2><%= @squirrel.squirrel_name %></h2>
      <p class="description-profile">"Something Here"</p>
      <p class="email-s"><%= @squirrel.email %></p>
    </div>


  </div>

</div>